import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='page'>
      <body className={inter.className}>
        <div className='layout'>
          <Header isArt />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
